from setuptools import setup

setup(name='lcfcn',
      version='0.6.0',
      description='LCFCN',
      url='git@github.com:ElementAI/LCFCN.git',
      maintainer='Issam Laradji',
      maintainer_email='issam.laradji@gmail.com',
      license='Apache 2.0',
      packages=['lcfcn'],
      zip_safe=False,
      install_requires=[
        'tqdm>=0.0',
        'numpy>=0.0',
        'pandas>=0.0',
        'Pillow>=0.0',
        'scikit-image>=0.0',
        'scikit-learn>=0.0',
        'scipy>=0.0',
        'sklearn>=0.0',
        'torch>=0.0',
        'torchvision>=0.0',
      ]),
